use ruffle_core::events::KeyCode;
use rust_libretro::sys::{retro_key, retro_mod};

// TODO: Write a proc_macro to simplify this
/// Assumes US layout
pub fn to_key_char(keycode: retro_key, key_modifiers: retro_mod) -> Option<char> {
    use rust_libretro::sys::retro_key as key;
    use rust_libretro::sys::retro_mod as kmod;

    match (key_modifiers, keycode) {
        // Letters
        (kmod::RETROKMOD_SHIFT, key::RETROK_a) => Some('A'),
        (_, key::RETROK_a) => Some('a'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_b) => Some('B'),
        (_, key::RETROK_b) => Some('b'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_c) => Some('C'),
        (_, key::RETROK_c) => Some('c'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_d) => Some('D'),
        (_, key::RETROK_d) => Some('d'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_e) => Some('E'),
        (_, key::RETROK_e) => Some('e'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_f) => Some('F'),
        (_, key::RETROK_f) => Some('f'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_g) => Some('G'),
        (_, key::RETROK_g) => Some('g'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_h) => Some('H'),
        (_, key::RETROK_h) => Some('h'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_i) => Some('I'),
        (_, key::RETROK_i) => Some('i'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_j) => Some('J'),
        (_, key::RETROK_j) => Some('j'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_k) => Some('K'),
        (_, key::RETROK_k) => Some('k'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_l) => Some('L'),
        (_, key::RETROK_l) => Some('l'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_m) => Some('M'),
        (_, key::RETROK_m) => Some('m'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_n) => Some('N'),
        (_, key::RETROK_n) => Some('n'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_o) => Some('O'),
        (_, key::RETROK_o) => Some('o'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_p) => Some('P'),
        (_, key::RETROK_p) => Some('p'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_q) => Some('Q'),
        (_, key::RETROK_q) => Some('q'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_r) => Some('R'),
        (_, key::RETROK_r) => Some('r'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_s) => Some('S'),
        (_, key::RETROK_s) => Some('s'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_t) => Some('T'),
        (_, key::RETROK_t) => Some('t'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_u) => Some('U'),
        (_, key::RETROK_u) => Some('u'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_v) => Some('V'),
        (_, key::RETROK_v) => Some('v'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_w) => Some('W'),
        (_, key::RETROK_w) => Some('w'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_x) => Some('X'),
        (_, key::RETROK_x) => Some('x'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_y) => Some('Y'),
        (_, key::RETROK_y) => Some('y'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_z) => Some('Z'),
        (_, key::RETROK_z) => Some('z'),

        // Numbers
        (kmod::RETROKMOD_SHIFT, key::RETROK_1) => Some('!'),
        (_, key::RETROK_1) => Some('1'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_2) => Some('@'),
        (_, key::RETROK_2) => Some('2'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_3) => Some('#'),
        (_, key::RETROK_3) => Some('3'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_4) => Some('$'),
        (_, key::RETROK_4) => Some('4'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_5) => Some('%'),
        (_, key::RETROK_5) => Some('5'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_6) => Some('^'),
        (_, key::RETROK_6) => Some('6'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_7) => Some('&'),
        (_, key::RETROK_7) => Some('7'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_8) => Some('*'),
        (_, key::RETROK_8) => Some('8'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_9) => Some('('),
        (_, key::RETROK_9) => Some('9'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_0) => Some(')'),
        (_, key::RETROK_0) => Some('0'),

        // Punctuation, no Shift
        (_, key::RETROK_TAB) => Some('\t'),
        (_, key::RETROK_RETURN) => Some('\n'),
        (_, key::RETROK_SPACE) => Some(' '),
        (_, key::RETROK_EXCLAIM) => Some('!'),
        (_, key::RETROK_QUOTEDBL) => Some('"'),
        (_, key::RETROK_HASH) => Some('#'),
        (_, key::RETROK_DOLLAR) => Some('$'),
        (_, key::RETROK_AMPERSAND) => Some('&'),
        (_, key::RETROK_QUOTE) => Some('\''),
        (_, key::RETROK_LEFTPAREN) => Some('('),
        (_, key::RETROK_RIGHTPAREN) => Some(')'),
        (_, key::RETROK_ASTERISK) => Some('*'),
        (_, key::RETROK_PLUS) => Some('+'),
        (_, key::RETROK_COLON) => Some(':'),
        (_, key::RETROK_LESS) => Some('<'),
        (_, key::RETROK_GREATER) => Some('>'),
        (_, key::RETROK_QUESTION) => Some('?'),
        (_, key::RETROK_AT) => Some('@'),
        (_, key::RETROK_CARET) => Some('^'),
        (_, key::RETROK_UNDERSCORE) => Some('_'),
        (_, key::RETROK_LEFTBRACE) => Some('{'),
        (_, key::RETROK_RIGHTBRACE) => Some('}'),
        (_, key::RETROK_TILDE) => Some('~'),
        (_, key::RETROK_BACKSPACE) => Some('\x08'),
        (_, key::RETROK_EURO) => Some('€'),

        // Punctuation with Shift
        (kmod::RETROKMOD_SHIFT, key::RETROK_COMMA) => Some('<'),
        (_, key::RETROK_COMMA) => Some(','),
        (kmod::RETROKMOD_SHIFT, key::RETROK_MINUS) => Some('_'),
        (_, key::RETROK_MINUS) => Some('-'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_PERIOD) => Some('>'),
        (_, key::RETROK_PERIOD) => Some('.'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_SLASH) => Some('?'),
        (_, key::RETROK_SLASH) => Some('/'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_SEMICOLON) => Some(':'),
        (_, key::RETROK_SEMICOLON) => Some(';'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_EQUALS) => Some('+'),
        (_, key::RETROK_EQUALS) => Some('='),
        (kmod::RETROKMOD_SHIFT, key::RETROK_LEFTBRACKET) => Some('{'),
        (_, key::RETROK_LEFTBRACKET) => Some('['),
        (kmod::RETROKMOD_SHIFT, key::RETROK_BACKSLASH) => Some('|'),
        (_, key::RETROK_BACKSLASH) => Some('\\'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_RIGHTBRACKET) => Some('}'),
        (_, key::RETROK_RIGHTBRACKET) => Some(']'),
        (kmod::RETROKMOD_SHIFT, key::RETROK_BACKQUOTE) => Some('~'),
        (_, key::RETROK_BACKQUOTE) => Some('`'),

        // Numpad
        (_, key::RETROK_KP0) => Some('0'),
        (_, key::RETROK_KP1) => Some('1'),
        (_, key::RETROK_KP2) => Some('2'),
        (_, key::RETROK_KP3) => Some('3'),
        (_, key::RETROK_KP4) => Some('4'),
        (_, key::RETROK_KP5) => Some('5'),
        (_, key::RETROK_KP6) => Some('6'),
        (_, key::RETROK_KP7) => Some('7'),
        (_, key::RETROK_KP8) => Some('8'),
        (_, key::RETROK_KP9) => Some('9'),
        (_, key::RETROK_KP_PERIOD) => Some('.'),
        (_, key::RETROK_KP_DIVIDE) => Some('/'),
        (_, key::RETROK_KP_MULTIPLY) => Some('*'),
        (_, key::RETROK_KP_MINUS) => Some('-'),
        (_, key::RETROK_KP_PLUS) => Some('+'),
        (_, key::RETROK_KP_ENTER) => Some('\n'),
        (_, key::RETROK_KP_EQUALS) => Some('='),

        _ => None,
    }
}

/// Assumes US layout
pub fn to_key_code(key: retro_key) -> KeyCode {
    use ruffle_core::events::KeyCode::*;
    match key {
        retro_key::RETROK_UNKNOWN => Unknown,
        retro_key::RETROK_BACKSPACE => Backspace,
        retro_key::RETROK_TAB => Tab,
        retro_key::RETROK_CLEAR => Unknown,
        retro_key::RETROK_RETURN => Return,
        retro_key::RETROK_PAUSE => Pause,
        retro_key::RETROK_ESCAPE => Escape,
        retro_key::RETROK_SPACE => Space,
        retro_key::RETROK_EXCLAIM => Key1,
        retro_key::RETROK_QUOTEDBL => Apostrophe,
        retro_key::RETROK_HASH => Key3,
        retro_key::RETROK_DOLLAR => Key4,
        retro_key::RETROK_AMPERSAND => Key7,
        retro_key::RETROK_QUOTE => Apostrophe,
        retro_key::RETROK_LEFTPAREN => Key9,
        retro_key::RETROK_RIGHTPAREN => Key0,
        retro_key::RETROK_ASTERISK => Key8,
        retro_key::RETROK_PLUS => Plus,
        retro_key::RETROK_COMMA => Comma,
        retro_key::RETROK_MINUS => Minus,
        retro_key::RETROK_PERIOD => Period,
        retro_key::RETROK_SLASH => Slash,
        retro_key::RETROK_0 => Key0,
        retro_key::RETROK_1 => Key1,
        retro_key::RETROK_2 => Key2,
        retro_key::RETROK_3 => Key3,
        retro_key::RETROK_4 => Key4,
        retro_key::RETROK_5 => Key5,
        retro_key::RETROK_6 => Key6,
        retro_key::RETROK_7 => Key7,
        retro_key::RETROK_8 => Key8,
        retro_key::RETROK_9 => Key9,
        retro_key::RETROK_COLON => Semicolon,
        retro_key::RETROK_SEMICOLON => Semicolon,
        retro_key::RETROK_LESS => Comma,
        retro_key::RETROK_EQUALS => Equals,
        retro_key::RETROK_GREATER => Period,
        retro_key::RETROK_QUESTION => Slash,
        retro_key::RETROK_AT => Key2,
        retro_key::RETROK_LEFTBRACKET => LBracket,
        retro_key::RETROK_BACKSLASH => Backslash,
        retro_key::RETROK_RIGHTBRACKET => RBracket,
        retro_key::RETROK_CARET => Key6,
        retro_key::RETROK_UNDERSCORE => Minus,
        retro_key::RETROK_BACKQUOTE => Grave,
        retro_key::RETROK_a => A,
        retro_key::RETROK_b => B,
        retro_key::RETROK_c => C,
        retro_key::RETROK_d => D,
        retro_key::RETROK_e => E,
        retro_key::RETROK_f => F,
        retro_key::RETROK_g => G,
        retro_key::RETROK_h => H,
        retro_key::RETROK_i => I,
        retro_key::RETROK_j => J,
        retro_key::RETROK_k => K,
        retro_key::RETROK_l => L,
        retro_key::RETROK_m => M,
        retro_key::RETROK_n => N,
        retro_key::RETROK_o => O,
        retro_key::RETROK_p => P,
        retro_key::RETROK_q => Q,
        retro_key::RETROK_r => R,
        retro_key::RETROK_s => S,
        retro_key::RETROK_t => T,
        retro_key::RETROK_u => U,
        retro_key::RETROK_v => V,
        retro_key::RETROK_w => W,
        retro_key::RETROK_x => X,
        retro_key::RETROK_y => Y,
        retro_key::RETROK_z => Z,
        retro_key::RETROK_LEFTBRACE => LBracket,
        retro_key::RETROK_BAR => Unknown,
        retro_key::RETROK_RIGHTBRACE => RBracket,
        retro_key::RETROK_TILDE => Apostrophe,
        retro_key::RETROK_DELETE => Delete,

        retro_key::RETROK_KP0 => Numpad0,
        retro_key::RETROK_KP1 => Numpad1,
        retro_key::RETROK_KP2 => Numpad2,
        retro_key::RETROK_KP3 => Numpad3,
        retro_key::RETROK_KP4 => Numpad4,
        retro_key::RETROK_KP5 => Numpad5,
        retro_key::RETROK_KP6 => Numpad6,
        retro_key::RETROK_KP7 => Numpad7,
        retro_key::RETROK_KP8 => Numpad8,
        retro_key::RETROK_KP9 => Numpad9,
        retro_key::RETROK_KP_PERIOD => NumpadPeriod,
        retro_key::RETROK_KP_DIVIDE => NumpadSlash,
        retro_key::RETROK_KP_MULTIPLY => Multiply,
        retro_key::RETROK_KP_MINUS => NumpadMinus,
        retro_key::RETROK_KP_PLUS => Plus,
        retro_key::RETROK_KP_ENTER => NumpadEnter,
        retro_key::RETROK_KP_EQUALS => Equals,

        retro_key::RETROK_UP => Up,
        retro_key::RETROK_DOWN => Down,
        retro_key::RETROK_RIGHT => Right,
        retro_key::RETROK_LEFT => Left,
        retro_key::RETROK_INSERT => Insert,
        retro_key::RETROK_HOME => Home,
        retro_key::RETROK_END => End,
        retro_key::RETROK_PAGEUP => PgUp,
        retro_key::RETROK_PAGEDOWN => PgDown,

        retro_key::RETROK_F1 => F1,
        retro_key::RETROK_F2 => F2,
        retro_key::RETROK_F3 => F3,
        retro_key::RETROK_F4 => F4,
        retro_key::RETROK_F5 => F5,
        retro_key::RETROK_F6 => F6,
        retro_key::RETROK_F7 => F7,
        retro_key::RETROK_F8 => F8,
        retro_key::RETROK_F9 => F9,
        retro_key::RETROK_F10 => F10,
        retro_key::RETROK_F11 => F11,
        retro_key::RETROK_F12 => F12,
        retro_key::RETROK_F13 => F13,
        retro_key::RETROK_F14 => F14,
        retro_key::RETROK_F15 => F15,

        retro_key::RETROK_NUMLOCK => Numpad,
        retro_key::RETROK_CAPSLOCK => CapsLock,
        retro_key::RETROK_SCROLLOCK => ScrollLock,
        retro_key::RETROK_RSHIFT => Shift,
        retro_key::RETROK_LSHIFT => Shift,
        retro_key::RETROK_RCTRL => Control,
        retro_key::RETROK_LCTRL => Control,
        retro_key::RETROK_RALT => Alt,
        retro_key::RETROK_LALT => Alt,
        retro_key::RETROK_RMETA => Unknown,
        retro_key::RETROK_LMETA => Unknown,
        retro_key::RETROK_LSUPER => Unknown,
        retro_key::RETROK_RSUPER => Unknown,
        retro_key::RETROK_MODE => Unknown,
        retro_key::RETROK_COMPOSE => Unknown,

        retro_key::RETROK_HELP => Unknown,
        retro_key::RETROK_PRINT => Unknown,
        retro_key::RETROK_SYSREQ => Unknown,
        retro_key::RETROK_BREAK => Unknown,
        retro_key::RETROK_MENU => Unknown,
        retro_key::RETROK_POWER => Unknown,
        retro_key::RETROK_EURO => Unknown,
        retro_key::RETROK_UNDO => Unknown,
        retro_key::RETROK_OEM_102 => Unknown,
        _ => Unknown,
    }
}
