use ruffle_core::events::KeyCode;
use rust_libretro::sys::retro_key;

pub trait From<T>: Sized {
    /// Converts to this type from the input type.
    fn from(value: T) -> Self;
}

impl From<retro_key> for KeyCode {
    fn from(item: retro_key) -> Self {
        use KeyCode::*;
        // TODO: Probably not amenable to different keyboard layouts
        match item {
            retro_key::RETROK_UNKNOWN => Unknown,
            retro_key::RETROK_BACKSPACE => Backspace,
            retro_key::RETROK_TAB => Tab,
            retro_key::RETROK_CLEAR => 0,
            retro_key::RETROK_RETURN => Return,
            retro_key::RETROK_PAUSE => Pause,
            retro_key::RETROK_ESCAPE => Escape,
            retro_key::RETROK_SPACE => Space,
            retro_key::RETROK_EXCLAIM => 33,
            retro_key::RETROK_QUOTEDBL => 34,
            retro_key::RETROK_HASH => 0,
            retro_key::RETROK_DOLLAR => 0,
            retro_key::RETROK_AMPERSAND => 0,
            retro_key::RETROK_QUOTE => Apostrophe,
            retro_key::RETROK_LEFTPAREN => 40,
            retro_key::RETROK_RIGHTPAREN => 41,
            retro_key::RETROK_ASTERISK => 42,
            retro_key::RETROK_PLUS => Plus,
            retro_key::RETROK_COMMA => Comma,
            retro_key::RETROK_MINUS => Minus,
            retro_key::RETROK_PERIOD => Period,
            retro_key::RETROK_SLASH => Slash,
            retro_key::RETROK_0 => Key0,
            retro_key::RETROK_1 => Key1,
            retro_key::RETROK_2 => Key2,
            retro_key::RETROK_3 => Key3,
            retro_key::RETROK_4 => Key4,
            retro_key::RETROK_5 => Key5,
            retro_key::RETROK_6 => Key6,
            retro_key::RETROK_7 => Key7,
            retro_key::RETROK_8 => Key8,
            retro_key::RETROK_9 => Key9,
            retro_key::RETROK_COLON => 58,
            retro_key::RETROK_SEMICOLON => Semicolon,
            retro_key::RETROK_LESS => 60,
            retro_key::RETROK_EQUALS => Equals,
            retro_key::RETROK_GREATER => 62,
            retro_key::RETROK_QUESTION => 63,
            retro_key::RETROK_AT => 64,
            retro_key::RETROK_LEFTBRACKET => LBracket,
            retro_key::RETROK_BACKSLASH => Backslash,
            retro_key::RETROK_RIGHTBRACKET => RBracket,
            retro_key::RETROK_CARET => 0,
            retro_key::RETROK_UNDERSCORE => 0,
            retro_key::RETROK_BACKQUOTE => Grave,
            retro_key::RETROK_a => A,
            retro_key::RETROK_b => B,
            retro_key::RETROK_c => C,
            retro_key::RETROK_d => D,
            retro_key::RETROK_e => E,
            retro_key::RETROK_f => F,
            retro_key::RETROK_g => G,
            retro_key::RETROK_h => H,
            retro_key::RETROK_i => I,
            retro_key::RETROK_j => J,
            retro_key::RETROK_k => K,
            retro_key::RETROK_l => L,
            retro_key::RETROK_m => M,
            retro_key::RETROK_n => N,
            retro_key::RETROK_o => O,
            retro_key::RETROK_p => P,
            retro_key::RETROK_q => Q,
            retro_key::RETROK_r => R,
            retro_key::RETROK_s => S,
            retro_key::RETROK_t => T,
            retro_key::RETROK_u => U,
            retro_key::RETROK_v => V,
            retro_key::RETROK_w => W,
            retro_key::RETROK_x => X,
            retro_key::RETROK_y => Y,
            retro_key::RETROK_z => Z,
            retro_key::RETROK_LEFTBRACE => 123,
            retro_key::RETROK_BAR => 124,
            retro_key::RETROK_RIGHTBRACE => 125,
            retro_key::RETROK_TILDE => 126,
            retro_key::RETROK_DELETE => Delete,

            retro_key::RETROK_KP0 => Numpad0,
            retro_key::RETROK_KP1 => Numpad1,
            retro_key::RETROK_KP2 => Numpad2,
            retro_key::RETROK_KP3 => Numpad3,
            retro_key::RETROK_KP4 => Numpad4,
            retro_key::RETROK_KP5 => Numpad5,
            retro_key::RETROK_KP6 => Numpad6,
            retro_key::RETROK_KP7 => Numpad7,
            retro_key::RETROK_KP8 => Numpad8,
            retro_key::RETROK_KP9 => Numpad9,
            retro_key::RETROK_KP_PERIOD => NumpadPeriod,
            retro_key::RETROK_KP_DIVIDE => NumpadSlash,
            retro_key::RETROK_KP_MULTIPLY => Multiply,
            retro_key::RETROK_KP_MINUS => NumpadMinus,
            retro_key::RETROK_KP_PLUS => 0,
            retro_key::RETROK_KP_ENTER => NumpadEnter,
            retro_key::RETROK_KP_EQUALS => 272,

            retro_key::RETROK_UP => Up,
            retro_key::RETROK_DOWN => Down,
            retro_key::RETROK_RIGHT => Right,
            retro_key::RETROK_LEFT => Left,
            retro_key::RETROK_INSERT => Insert,
            retro_key::RETROK_HOME => Home,
            retro_key::RETROK_END => End,
            retro_key::RETROK_PAGEUP => PgUp,
            retro_key::RETROK_PAGEDOWN => PgDown,

            retro_key::RETROK_F1 => F1,
            retro_key::RETROK_F2 => F2,
            retro_key::RETROK_F3 => F3,
            retro_key::RETROK_F4 => F4,
            retro_key::RETROK_F5 => F5,
            retro_key::RETROK_F6 => F6,
            retro_key::RETROK_F7 => F7,
            retro_key::RETROK_F8 => F8,
            retro_key::RETROK_F9 => F9,
            retro_key::RETROK_F10 => F10,
            retro_key::RETROK_F11 => F11,
            retro_key::RETROK_F12 => F12,
            retro_key::RETROK_F13 => F13,
            retro_key::RETROK_F14 => F14,
            retro_key::RETROK_F15 => F15,

            retro_key::RETROK_NUMLOCK => Numpad,
            retro_key::RETROK_CAPSLOCK => CapsLock,
            retro_key::RETROK_SCROLLOCK => ScrollLock,
            retro_key::RETROK_RSHIFT => Shift,
            retro_key::RETROK_LSHIFT => Shift,
            retro_key::RETROK_RCTRL => Control,
            retro_key::RETROK_LCTRL => Control,
            retro_key::RETROK_RALT => Alt,
            retro_key::RETROK_LALT => Alt,
            retro_key::RETROK_RMETA => 309,
            retro_key::RETROK_LMETA => 310,
            retro_key::RETROK_LSUPER => Unknown,
            retro_key::RETROK_RSUPER => Unknown,
            retro_key::RETROK_MODE => Unknown,
            retro_key::RETROK_COMPOSE => 314,

            retro_key::RETROK_HELP => Unknown,
            retro_key::RETROK_PRINT => Unknown,
            retro_key::RETROK_SYSREQ => Unknown,
            retro_key::RETROK_BREAK => Unknown,
            retro_key::RETROK_MENU => Unknown,
            retro_key::RETROK_POWER => Unknown,
            retro_key::RETROK_EURO => Unknown,
            retro_key::RETROK_UNDO => Unknown,
            retro_key::RETROK_OEM_102 => Unknown,
        }
    }
}